# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cantango-permits}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Kristian Mandrup}, %q{Stanislaw Pankevich}]
  s.date = %q{2011-12-24}
  s.description = %q{Permit classes and engine for CanTango}
  s.email = %q{kmandrup@gmail.com, s.pankevich@gmail.com}
  s.extra_rdoc_files = [
    "README.mdown"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "lib/cantango/executor.rb",
    "lib/cantango/executor/base.rb",
    "lib/cantango/executor/permit.rb",
    "lib/cantango/executor/permit/abstract.rb",
    "lib/cantango/executor/permit/base.rb",
    "lib/cantango/executor/permit/special.rb",
    "lib/cantango/executor/permit_type.rb",
    "lib/cantango/license.rb",
    "lib/cantango/license/rules.rb",
    "lib/cantango/permit.mdown",
    "lib/cantango/permit.rb",
    "lib/cantango/permit/account_type.rb",
    "lib/cantango/permit/attribute.rb",
    "lib/cantango/permit/base.rb",
    "lib/cantango/permit/class_methods.rb",
    "lib/cantango/permit/helper.rb",
    "lib/cantango/permit/helper/execution.rb",
    "lib/cantango/permit/helper/host.rb",
    "lib/cantango/permit/helper/license.rb",
    "lib/cantango/permit/helper/naming.rb",
    "lib/cantango/permit/helper/state.rb",
    "lib/cantango/permit/special.rb",
    "lib/cantango/permit/user.rb",
    "lib/cantango/permit/user_type.rb",
    "lib/cantango/permits.rb",
    "lib/cantango/permits_ext.rb",
    "lib/cantango/permits_ext/ability.rb",
    "lib/cantango/permits_ext/ability/helper.rb",
    "lib/cantango/permits_ext/ability/helper/permits.rb",
    "lib/cantango/permits_ext/builder.rb",
    "lib/cantango/permits_ext/builder/permit.rb",
    "lib/cantango/permits_ext/builder/permit/account_type.rb",
    "lib/cantango/permits_ext/builder/permit/base.rb",
    "lib/cantango/permits_ext/builder/permit/special.rb",
    "lib/cantango/permits_ext/builder/permit/user_type.rb",
    "lib/cantango/permits_ext/class_methods.rb",
    "lib/cantango/permits_ext/config.rb",
    "lib/cantango/permits_ext/config/engines.rb",
    "lib/cantango/permits_ext/config/engines/permit.rb",
    "lib/cantango/permits_ext/config/permits.rb",
    "lib/cantango/permits_ext/config/permits/accounts.rb",
    "lib/cantango/permits_ext/config/permits/disabling.rb",
    "lib/cantango/permits_ext/config/permits/enabling.rb",
    "lib/cantango/permits_ext/config/permits/execution.rb",
    "lib/cantango/permits_ext/config/permits/key.rb",
    "lib/cantango/permits_ext/config/permits/registration.rb",
    "lib/cantango/permits_ext/config/permits/tracking.rb",
    "lib/cantango/permits_ext/config/permits/types.rb",
    "lib/cantango/permits_ext/engine.rb",
    "lib/cantango/permits_ext/engine/permits.rb",
    "lib/cantango/permits_ext/factory.rb",
    "lib/cantango/permits_ext/factory/permits.rb",
    "lib/cantango/permits_ext/finder.rb",
    "lib/cantango/permits_ext/finder/base.rb",
    "lib/cantango/permits_ext/finder/permit.rb",
    "lib/cantango/permits_ext/finder/permit/account.rb",
    "lib/cantango/permits_ext/finder/permit/base.rb",
    "lib/cantango/permits_ext/loader.rb",
    "lib/cantango/permits_ext/loader/categories.rb",
    "lib/cantango/permits_ext/loader/license.rb",
    "lib/cantango/permits_ext/macros.rb",
    "lib/cantango/permits_ext/macros/permit.rb",
    "lib/cantango/permits_ext/parser.rb",
    "lib/cantango/permits_ext/parser/categories.rb",
    "lib/cantango/permits_ext/registry.rb",
    "lib/cantango/permits_ext/registry/permit.rb",
    "lib/generators/cantango/account_permit/account_permit_generator.rb",
    "lib/generators/cantango/account_permit/templates/account_permit.erb",
    "lib/generators/cantango/base.rb",
    "lib/generators/cantango/basic.rb",
    "lib/generators/cantango/license/license_generator.rb",
    "lib/generators/cantango/license/templates/license.erb",
    "lib/generators/cantango/license_base.rb",
    "lib/generators/cantango/licenses/licenses_generator.rb",
    "lib/generators/cantango/permit_generator.rb",
    "lib/generators/cantango/role_permit/role_permit_generator.rb",
    "lib/generators/cantango/role_permit/templates/account_permit.erb",
    "lib/generators/cantango/role_permit/templates/role_group_permit.erb",
    "lib/generators/cantango/role_permit/templates/role_permit.erb",
    "lib/generators/cantango/role_permits/role_permits_generator.rb",
    "lib/generators/cantango/user_permit/templates/account_permit.erb",
    "lib/generators/cantango/user_permit/templates/user_permit.erb",
    "lib/generators/cantango/user_permit/user_permit_generator.rb",
    "lib/tasks/permits_tasks.rake",
    "spec/cantango/ability/helper/permits_spec.rb",
    "spec/cantango/builder/permit/account_type_spec.rb",
    "spec/cantango/builder/permit/base_spec.rb",
    "spec/cantango/builder/permit/special_spec.rb",
    "spec/cantango/builder/permit/user_type_spec.rb",
    "spec/cantango/config/engines/permit_spec.rb",
    "spec/cantango/config/engines_spec.rb",
    "spec/cantango/config/permit_registry_ex.rb",
    "spec/cantango/config/permit_registry_spec.rb",
    "spec/cantango/config/permits/accounts_spec.rb",
    "spec/cantango/config/permits/disabling_spec.rb",
    "spec/cantango/config/permits/enabling_spec.rb",
    "spec/cantango/config/permits/execution_spec.rb",
    "spec/cantango/config/permits/registration_spec.rb",
    "spec/cantango/config/permits/tracking_spec.rb",
    "spec/cantango/config/permits/types_spec.rb",
    "spec/cantango/config/permits_spec.rb",
    "spec/cantango/engine/permit_cached_spec.rb",
    "spec/cantango/engine/permit_spec.rb",
    "spec/cantango/engine/permit_static_dynamic_spec.rb",
    "spec/cantango/executor/custom_permit_spec.rb",
    "spec/cantango/executor/more_permit_spec.rb",
    "spec/cantango/executor/permit_base_spec.rb",
    "spec/cantango/executor/permit_spec.rb",
    "spec/cantango/executor/special_permit_spec.rb",
    "spec/cantango/factory/permits_spec.rb",
    "spec/cantango/finder/account_permit_spec.rb",
    "spec/cantango/finder/permit_spec.rb",
    "spec/cantango/license/save_license_spec.rb",
    "spec/cantango/license_spec.rb",
    "spec/cantango/loader/categories_spec.rb",
    "spec/cantango/loader/license_spec.rb",
    "spec/cantango/macros/permit_spec.rb",
    "spec/cantango/parser/categories_spec.rb",
    "spec/cantango/permit/account_type_spec.rb",
    "spec/cantango/permit/attribute_permit_spec.rb",
    "spec/cantango/permit/base_spec.rb",
    "spec/cantango/permit/class_methods_spec.rb",
    "spec/cantango/permit/helper/execution_spec.rb",
    "spec/cantango/permit/helper/host_spec.rb",
    "spec/cantango/permit/helper/license_spec.rb",
    "spec/cantango/permit/helper/naming_spec.rb",
    "spec/cantango/permit/helper/state_spec.rb",
    "spec/cantango/permit/special_default_spec.rb",
    "spec/cantango/permit/special_first_spec.rb",
    "spec/cantango/permit/user_type_spec.rb",
    "spec/cantango/registry/permit_spec.rb",
    "spec/fixtures/config/cantango_permissions.yml",
    "spec/fixtures/config/categories.yml",
    "spec/fixtures/config/evaluator_fixtures.yml",
    "spec/fixtures/config/licenses.yml",
    "spec/fixtures/config/permissions.yml",
    "spec/fixtures/config/role_group.yml",
    "spec/fixtures/config/roles.yml",
    "spec/fixtures/config/test_permissions.yml",
    "spec/fixtures/config/user_permissions.yml",
    "spec/fixtures/models.rb",
    "spec/fixtures/models/admin.rb",
    "spec/fixtures/models/admin_account.rb",
    "spec/fixtures/models/items.rb",
    "spec/fixtures/models/permission.rb",
    "spec/fixtures/models/simple_roles.rb",
    "spec/fixtures/models/user.rb",
    "spec/fixtures/models/user_account.rb",
    "spec/fixtures/tango_fixtures.rb",
    "spec/generators/cantango/account_role_permit_generator_spec.rb",
    "spec/generators/cantango/account_role_permits_generator_spec.rb",
    "spec/generators/cantango/license_generator_spec.rb",
    "spec/generators/cantango/licenses_generator_spec.rb",
    "spec/generators/cantango/role_permit_generator_spec.rb",
    "spec/generators/cantango/role_permits_generator_spec.rb",
    "spec/helpers/current_user_accounts.rb",
    "spec/helpers/current_users.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/cantango-permits}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Permits with engine for cantango}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<sweetloader>, [">= 0.1.6"])
      s.add_runtime_dependency(%q<hashie>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<cantango-config>, ["~> 0.2.0"])
      s.add_runtime_dependency(%q<cantango-api>, [">= 0.1.3"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.1"])
      s.add_dependency(%q<sugar-high>, [">= 0.6.1"])
      s.add_dependency(%q<sweetloader>, [">= 0.1.6"])
      s.add_dependency(%q<hashie>, [">= 1.2.0"])
      s.add_dependency(%q<cantango-config>, ["~> 0.2.0"])
      s.add_dependency(%q<cantango-api>, [">= 0.1.3"])
      s.add_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1"])
    s.add_dependency(%q<sugar-high>, [">= 0.6.1"])
    s.add_dependency(%q<sweetloader>, [">= 0.1.6"])
    s.add_dependency(%q<hashie>, [">= 1.2.0"])
    s.add_dependency(%q<cantango-config>, ["~> 0.2.0"])
    s.add_dependency(%q<cantango-api>, [">= 0.1.3"])
    s.add_dependency(%q<bundler>, [">= 1.1.rc"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
  end
end

